:showtitle:
:toc: left
:icons: font
:toclevels: 1

= Dropshot Changelog

// cargo-release: next header goes here (do not change this line)

== Unreleased changes (release date TBD)

https://github.com/oxidecomputer/dropshot/compare/v0.4.0\...HEAD[Full list of commits]

// WARNING: This file is modified programmatically by `cargo release` as
// configured in release.toml.  DO NOT change the format of the headers or the
// list of raw commits.

=== Breaking Changes

==== Generic Context

* https://github.com/oxidecomputer/dropshot/pull/86[#86] Dropshot now uses generics to store client context, rather than relying on an internal `Any` object within `RequestContext`. Endpoints signatures are expected to begin with the argument `rqctx: Arc<RequestContext<CallerContext>>`, for some `CallerContext` object, and they may call `rqtcx.context()` to access the inner type.
* To provide this generic context, many Dropshot types are now generic, acting on a specialized context object (this includes `ApiDescription`, `ApiEndpoint`, `OpenApiDefinition`, `HttpServer`, `HttpServerStarter`, and `RequestContext`). For the most part, the specialization is made implicit by passing the context argument to an `HttpServerStarter` (formerly `HttpServer`).

```rust
struct ExampleContext { ... }

// Old Version:
#[endpoint { method = GET, path = "/endpoint" }]
pub async fn example_endpoint(
    rqctx: Arc<RequestContext>,
) -> Result<HttpResponseOk<...>, HttpError> {
    let ctx: Arc<dyn Any + Send + Sync + 'static> = Arc::clone(&rqctx.server.private);
    let example_context = ctx.downcast::<ExampleContext>().expect("Wrong type");
    ...
}

// New Version
#[endpoint { method = GET, path = "/endpoint" }]
pub async fn example_endpoint(
    rqctx: Arc<RequestContext<ExampleContext>>,
) -> Result<HttpResponseOk<...>, HttpError> {
    let example_context = rqctx.context();
    ...
}
```

==== HttpServer

See https://github.com/oxidecomputer/dropshot/pull/81[#81 for details]

===== HttpServer Split in Two
* In the old implementation, `HttpServer` represented both a pending and running server. Callers were expected to invoke `run()` to begin execution of the old server.
* In the new implementation, `HttpServerStarter` may be used to construct a server, and `HttpServer` represents the running server. Invoking `HttpServerStarter::start()` creates and `HttpServer` object, which represents the new server.

===== HttpServer implements Future
* In the old implementation, `HttpServer` returned a `tokio::JoinHandle`, and callers were expected to invoke `wait_for_shutdown` to await the completion of a server.
* In the new implementation, `HttpServer` implements `Future`, and may be `await`-ed directly.

===== Example

```rust
// Old Version:
let mut server = HttpServer::new( /* Arguments are the same between versions */ )
  .map_err(|error| format!("failed to start server: {}", error))?;

let server_task = server.run();
server.wait_for_shutdown(server_task).await;

// New Version
let server = HttpServerStarter::new( /* Arguments are the same between versions */ )
  .map_err(|error| format!("failed to start server: {}", error))?
  .start();

server.await;
```

=== Notable changes

* https://github.com/oxidecomputer/dropshot/issues/44[#44] The new extractor `UntypedBody` allows API endpoints to accept either raw bytes or a UTF-8 string.
* https://github.com/oxidecomputer/dropshot/pull/90[#90] `HttpError` now impls `std::error::Error`.

== 0.4.0 (released 2021-02-01)

https://github.com/oxidecomputer/dropshot/compare/v0.3.0\...v0.4.0[Full list of commits]

=== Breaking changes

* Dropshot now uses tokio 1.0 and hyper 0.14.  tokio 1.0 is incompatible at runtime with previous versions (0.2 and earlier).  Consumers must update to tokio 1.0 when updating to Dropshot {{version}}.  tokio does not expect to introduce new breaking changes in the foreseeable future, so we do not expect to have to do this again.

=== Deprecated

* `ApiDescription::print_openapi()` is now deprecated.  It's been replaced with `ApiDescription::openapi()`.  See #68 below.

=== Other notable changes

* https://github.com/oxidecomputer/dropshot/issues/68[#68] Improve ergonomics of OpenAPI definition generation.  This change deprecates `ApiDescription::print_openapi()`, replacing it with the easier-to-use `ApiDescription::openapi()`, which provides a builder interface.
* https://github.com/oxidecomputer/dropshot/issues/64[#64] The maximum request size is now configurable.  It defaults to the previously hardcoded value of 1024 bytes.  (The default is aggressive just to ensure test coverage.)
* https://github.com/oxidecomputer/dropshot/issues/61[#61] The schemars dependency is updated to 0.8.  Consumers must be using the same version of schemars.  (See https://github.com/oxidecomputer/dropshot/issues/67[#67].)

== Prior to 0.3.0

Changes not documented.
