:showtitle:
:toc: left
:icons: font

= Dropshot Maintainer's Notes

== Publishing a new release

This repo contains two Cargo packages: `dropshot` and `dropshot_endpoint`.  For simplicity, these two packages are always released together, and always with the same version number.

A release consists of:

* a git tag containing the version number (e.g., `v0.5.1`)
* publishing `dropshot` and `dropshot_endpoint` packages to crates.io

The release _process_ ensures a few things:

* Makes sure that we have git tags for the precise commits whose contents are published to crates.io.
* Sets the version numbers in Cargo.toml for the release.
* Updates the version numbers _after_ the release is done so that the version in Git accurately reflects that it's newer than the release you just published and older than the next actual release.  For example, if we published 0.5.2, then after the release the tooling sets the Cargo.toml version to 0.5.3-pre, which is after 0.5.2 and before 0.5.3.
* Updates the CHANGELOG.adoc file.  This moves the currently-unreleased changes to a new section for the version that you're publishing and sets us up with a new "Unreleased changes" section.

Here's how to cut a release.

. Check that the CHANGELOG.adoc file is up to date for this release.
.. Any notable changes should be documented.  There's a link in the changelog to a list of unreleased commits -- you can skim these to see if anything looks notable.
.. Any breaking changes should have text that concisely summarizes for a Dropshot user how they know if they're affected and what they need to do to safely upgrade their code.  A few minutes here can save many people many minutes later!
. Double-check your working directory.
.. `git status` should show that you're on the `main` branch.
.. Use `git pull` to sync up with any upstream changes.  `git status` should show that your local "main" is exactly sync'd up with the upstream "main" and that you have no uncommitted files or local changes to committed files.
.. `git clean -nxd` should be clean or close to it.  It should show nothing that should be checked into git and probably no stale build artifacts.
.. It's a good idea to check that CI completed successfully on GitHub for the commit that you've got checked out.  This will ensure that we're publishing a release that builds from scratch, passes all tests on all platforms, and passes our style and lint checks.
... Use `git log -1` to see what commit you're on.
... Look up that commit on GitHub.  It will have a URL like `https://github.com/oxidecomputer/dropshot/commit/COMMIT_SHA` (with an actual `COMMIT_SHA`).  CI succeeded if there's a green check at the left of the commit message.  You can click the green check to be sure you're looking at the right thing.  It should say "All checks have passed".
. Figure out the tag used for the most recent release.  The easiest is probably to view https://github.com/oxidecomputer/dropshot/releases[the recent releases].   We'll call this `PREV_RELEASE_TAG` in the next step.
. Figure out what kind of update this is relative to the last one released.  https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#bump-level[See `cargo release` docs for the available levels.]  We're usually doing a "patch", "minor", or "major" release.  We'll call this "RELEASE_KIND".
. Do the release.  If you're daring, just run:
+
[source,text]
----
$ cargo release --prev-tag-name=PREV_RELEASE_TAG -vv RELEASE_KIND
----
+
If you want to be extra careful, you can do this in a dry-run form.  First, check that the log output here looks right (and especially that you got the version number that you expected!):
+
[source,text]
----
$ cargo release --dry-run --prev-tag-name=PREV_RELEASE_TAG -vv RELEASE_KIND
----
+
Now, run `cargo release` for real (i.e. no `--dry-run`), but without publishing to crates.io or pushing the git tags:
+
[source,text]
----
$ cargo release --skip-push --skip-publish --prev-tag-name=PREV_RELEASE_TAG -vv minor
----
+
Inspect the resulting commits and the new tags from above.  There should be four commits: one to each of "dropshot" and "dropshot_endpoint" that sets the version to the one you specified, and one that sets the version to the _next_ version.  For example, if the current version is 0.5.1 and you're publishing 0.5.2, the repo will start at 0.5.2-pre, you'll see one commit that sets it to 0.5.2, and then you'll see one that sets it to 0.5.3-pre.
+
Then undo the above step:
+
[source,text]
----
$ git reset --hard THE_COMMIT_YOU_STARTED_WITH
$ git tag -d THE_NEW_TAG
----
+
and do the release again with the publish step:
+
[source,text]
----
$ cargo release --skip-push --prev-tag-name=PREV_RELEASE_TAG -vv minor
----
+
At this point, the new crates should be published to crates.io.  Check and
push the commits and the tags.
+
[source,text]
----
$ git push
$ git push --tags
----

=== Why all that checking?

dap's not familiar enough with Cargo to know what all the safeties are.  Other language package managers (well, npm) make it easy to publish packages that are missing files, contain extra files (like local-only notes or private keys), fail tests, etc.  The worst is not knowing the published package is broken or leaked private information until somebody reports it.

=== What if something goes wrong

At the end of the day, the release is just a git tag and the crates.io publish.

If something went wrong prior to the crates.io publish, then you can `git reset` to the commit you started with, delete your local tag, and try again.  (If you followed the above steps, you won't have pushed any git tags, so there's nothing on GitHub to undo.)

If something went wrong after the crates.io publish, you could try to fix up the Git state to match what it should be.  Or you could yank the version you published, reset your local state, and try again.


== Dependabot

TODO XXX
