# We use a specific toolchain revision to ensure our tests - which
# occasionally depend on specific compiler output - remain stable
# for all developers until the toolchain is explicitly advanced.

[toolchain]
channel = "1.57.0"
profile = "default"
