[package]
name = "dropshot-api-manager-example-bin"
version = "0.1.0"
edition = "2024"
license = "0BSD"
repository.workspace = true

[dependencies]
anyhow = "1.0.99"
camino = "1.2.0"
clap = { version = "4.5" }
dropshot-api-manager-example-apis.workspace = true
dropshot-api-manager-types.workspace = true
dropshot-api-manager.workspace = true
openapiv3 = { version = "2.2.0", features = [ "skip_serializing_defaults" ] }
openapi-lint = { git = "https://github.com/oxidecomputer/openapi-lint", branch = "main" }
serde = { version = "1.0.224", features = ["derive"] }
serde_json = "1.0.145"

[lints]
workspace = true
